[package]
org = "wso2"
name = "seasonal_discount_management"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.commerce.discounts"
version = "0.1.0"
repository = "local"
